services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=app_database'
      - 'MONGO_INITDB_ROOT_PASSWORD=123456'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
